### ISSUE TITLE
Unsafe usage of dictionary

### ISSUE THREAD

**Issue by GrabYourPitchforks** [adamsitnik/SafePayloadReader#3] opened 2024-03-04 21:09 UTC
https://github.com/adamsitnik/SafePayloadReader/blob/cfb7ac5e388fcfbe4e24fd034c282509b0a283aa/System.Runtime.Serialization.BinaryFormat/SafePayloadReader.cs#L138

`Dictionary<TKey, TValue>` (and related types like `HashSet<T>`) are safe for arbitrary user-provided keys _only when `TKey := string`_. In other cases, they are subject to hash collision DoS attacks, even in cases where the untrusted agent can provide int32 values.

The most straightforward fixes are: (a) always use `TKey := string` if possible; or (b) failing that, pass a custom hash collision resistant comparer into the dictionary ctor.

**Comment by adamsitnik** [comment] 2024-03-05 08:01
> (a) always use TKey := string if possible; or (b) failing that, pass a custom hash collision resistant comparer into the dictionary ctor

(a) would allocate some extra strings (it's not a big deal), but (b) sounds like a proper solution. I saw your code where you are using `HashCode.Combine` in `CollisionResistantInt32Comparer`. The problem is that it does not support .NET Standard 2.0.

What would be the NS2.0-compliant way to achieve that for integers?

**Comment by adamsitnik** [comment] 2024-03-05 09:13
Fixed with https://github.com/adamsitnik/SafePayloadReader/commit/a7c291af43221dfa2c89d6e88a3b19da53f96583

**Closed** 2024-03-07 08:25 UTC
